name: Deploy RC to DockerHub
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of Flex'
        required: true
      manifest:
        description: 'URL of Manifest'
        required: true

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  DeployRC:
    runs-on: ubuntu-latest
    name: Release RC
    steps:
      - uses: actions/checkout@v4
      - name: Verify RC version input
        run: |
          ./scripts/rc_release_check.sh ${{github.event.inputs.version}}
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Download and verify JAR(s)
        run: |
          ./scripts/jar.sh "${{github.event.inputs.manifest}}"
      - name: Release Flex JDK11 JAR
        run: |
          VERSION=${{github.event.inputs.version}}
          VERSION="${VERSION//./-}"
          aws s3 cp target/flex-java11-standalone.jar s3://${{ secrets.RELEASES_BUCKET }}/flex-$VERSION-java11.jar
      - name: Release Flex JDK8 JAR
        run: |
          VERSION=${{github.event.inputs.version}}
          VERSION="${VERSION//./-}"
          aws s3 cp target/flex-java8-standalone.jar s3://${{ secrets.RELEASES_BUCKET }}/flex-$VERSION-java8.jar
      - name: Release Flex JDK17 JAR
        run: |
          VERSION=${{github.event.inputs.version}}
          VERSION="${VERSION//./-}"
          aws s3 cp target/flex-java17-standalone.jar s3://${{ secrets.RELEASES_BUCKET }}/flex-$VERSION-java17.jar
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Flex
        run: |
          VERSION=${{github.event.inputs.version}}
          IMAGE_ID=factorhouse/flex
          IMAGE_TAG=$VERSION
          ./scripts/build_all.sh $VERSION $IMAGE_ID $IMAGE_TAG dockerfile/flex/Dockerfile
